services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    networks:
      - postgres-network

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    entrypoint: /bin/sh -c "/usr/bin/docker-entrypoint.sh server /data --console-address :9001"
    networks:
      - minio-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '1025:1025' # SMTP port
      - '8025:8025' # Web UI port
    networks:
      - mailhog-network

volumes:
  minio_data:

networks:
  postgres-network:
    driver: bridge
  minio-network:
    driver: bridge
  mailhog-network:
    driver: bridge
